#!/bin/sh
path=$(pwd)

# Home Directory
ln -sf $path/.bash_profile $HOME/.bash_profile
ln -sf $path/.bashrc $HOME/.bashrc
ln -sf $path/.profile $HOME/.profile
ln -sf $path/.zcompdump $HOME/.zcompdump
ln -sf $path/.zshenv $HOME/.zshenv
ln -sf $path/.zshrc $HOME/.zshrc
ln -sf $path/.vimrc $HOME/.vimrc
ln -sf $path/.tmux.conf $HOME/.tmux.conf
ln -sf $path/.tmux.conf.local $HOME/.tmux.conf.local

# Config dir
[ ! -d $HOME/.config ] && mkdir $HOME/.config

[ -d $HOME/.config/alacritty ] && rm -rf $HOME/.config/alacritty
ln -sf $path/config/alacritty $HOME/.config/alacritty

[ -d $HOME/.config/i3 ] && rm -rf $HOME/.config/i3
ln -sf $path/config/i3 $HOME/.config/i3

[ -d $HOME/.config/i3blocks ] && rm -rf $HOME/.config/i3blocks
ln -sf $path/config/i3blocks $HOME/.config/i3blocks

[ -d $HOME/.config/picom ] && rm -rf $HOME/.config/picom
ln -sf $path/config/picom $HOME/.config/picom

[ -d $HOME/.config/polybar ] && rm -rf $HOME/.config/polybar
ln -sf $path/config/polybar $HOME/.config/polybar

[ -d $HOME/.config/ranger ] && rm -rf $HOME/.config/ranger
ln -sf $path/config/ranger $HOME/.config/ranger

[ -d $HOME/.config/shellconfig ] && rm -rf $HOME/.config/shellconfig
ln -sf $path/config/shellconfig $HOME/.config/shellconfig

ln -sf $path/config/starship.toml $HOME/.config/starship.toml
# ln -sf $path/config/wall.png $HOME/.config/wall.png

[ ! -d $HOME/.config/skeletons ] && mkdir -p $HOME/.config/skeletons
ln -sf $path/config/skeletons $HOME/.config/skeletons

# Local directory
[ ! -d $HOME/.local ] && mkdir -p $HOME/.local/share
[ ! -d $HOME/.local/share ] && mkdir $HOME/.local/share
[ -d $HOME/.local/share/applications ] && rm -rf $HOME/.local/share/applications
ln -sf $path/.local/share/applications $HOME/.local/share/applications
[ -d $HOME/.local/share/fonts ] && rm -r $HOME/.local/share/fonts
ln -sf $path/.local/share/fonts $HOME/.local/share/fonts

sudo cp $path/config/vpn.sh /usr/local/bin/vpn
sudo cp $path/config/get_file_extensions /usr/local/bin/get_file_extensions
