#!/usr/bin/env sh
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="Hack Nerd Font:Regular:12.0"
ICON_FONT="Hack Nerd Font:Regular:13.0"

sketchybar --bar height=24 color=0xff1e1e2e border_width=0 padding_left=8 padding_right=8 topmost=window
sketchybar --default icon.font="$ICON_FONT" label.font="$FONT" label.color=0xffcdd6f4 icon.color=0xffcdd6f4 background.height=22 background.corner_radius=6 background.color=0xff313244 background.padding_left=6 background.padding_right=6

sketchybar --add event aerospace_workspace_change

for SID in 1 2 3 4 5 B C T M; do
  sketchybar --add item "space.$SID" left \
    --set "space.$SID" label="$SID" icon="" script="sh $PLUGIN_DIR/space.sh" click_script="aerospace workspace $SID" \
    --subscribe "space.$SID" aerospace_workspace_change
done

sketchybar --add item front_app left \
  --set front_app icon="" icon.padding_right=6 script="sh $PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar --add item app.aerospace left \
  --set app.aerospace icon="󰖲" label="" drawing=off click_script="open -a 'AeroSpace'"

sketchybar --add item app.kap left \
  --set app.kap icon="" label="" drawing=off click_script="open -a 'Kap'"

sketchybar --add item app.protonpass left \
  --set app.protonpass icon="󰌆" label="" drawing=off click_script="open -a 'Proton Pass'"

sketchybar --add item app.protonvpn left \
  --set app.protonvpn icon="󰌾" label="" drawing=off click_script="open -a 'Proton VPN'"

sketchybar --add item app.cursor left \
  --set app.cursor icon="󰞍" label="" drawing=off click_script="open -a 'Cursor'"

sketchybar --add item app_refresh left \
  --set app_refresh drawing=off script="sh $PLUGIN_DIR/apps.sh" update_freq=5

sketchybar --add item cpu right \
  --set cpu icon="" script="sh $PLUGIN_DIR/cpu.sh" update_freq=5 click_script="open -a 'Activity Monitor'"

sketchybar --add item ram right \
  --set ram icon="󰍛" script="sh $PLUGIN_DIR/ram.sh" update_freq=10 click_script="open -a 'Activity Monitor'"

sketchybar --add item net right \
  --set net icon="󰈀" script="sh $PLUGIN_DIR/net.sh" update_freq=2 click_script="open -a 'Activity Monitor'"

sketchybar --add item wifi right \
  --set wifi icon="" script="sh $PLUGIN_DIR/wifi.sh" update_freq=10 click_script="open 'x-apple.systempreferences:com.apple.preference.network?Wi-Fi'"

sketchybar --add item volume right \
  --set volume icon="" script="sh $PLUGIN_DIR/volume.sh" click_script="open 'x-apple.systempreferences:com.apple.preference.sound'" \
  --subscribe volume volume_change

sketchybar --add item battery right \
  --set battery icon="" script="sh $PLUGIN_DIR/battery.sh" update_freq=120 click_script="open 'x-apple.systempreferences:com.apple.preference.battery'" \
  --subscribe battery power_source_change

sketchybar --add item clock right \
  --set clock icon="" script="sh $PLUGIN_DIR/clock.sh" update_freq=60

sketchybar --add item media right \
  --set media icon="" script="sh $PLUGIN_DIR/media.sh" \
  --subscribe media media_change

sketchybar --update
