[prompt]
add_newline = false

[character]
symbol = ""


[python]
pyenv_version_name = true

[directory]
fish_style_pwd_dir_length = 10

[package]
symbol = "🎉 "

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[character]
use_symbol_for_status = true  # Show "✖" when the command faild

[directory]
truncation_length = 5
prefix = ""

[hostname]
ssh_only = false
prefix = "<"
suffix = ">"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[memory_usage]
show_percentage = true
show_swap = true
threshold = 50
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[time]
format = "🕙 %T"
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false
